version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=smarthouse
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./apps/backend_api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/smarthouse
      - ML_ENGINE_URL=http://ml_engine:8001
    depends_on:
      - db

  ml_engine:
    build:
      context: ./apps/ml_engine
    ports:
      - "8001:8001"
    environment:
      - BACKEND_API_URL=http://backend:8000
    volumes:
      - ./apps/ml_engine/models:/app/models

volumes:
  postgres_data:
